### ISSUE TITLE
Can't make a manual install of autotiling anymore

### ISSUE THREAD

**Issue by Lqp1** [nwg-piotr/autotiling#17]
Hello!

I'm not sure since when, but I noticed my autotiling setup was not starting anymore. Here's how I setup it:
* clone the repo
* start main.py using python3 interpreter.

I manually tried to run it, and here's what it says:
```
python main.py       
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from .__about__ import __version__
ImportError: attempted relative import with no known parent package
```

Could it be related to #14? I'm not sure how to workaround it?

If it's not possible anymore, can you update the README for future users please?

Thanks in advance for you inputs.

Br

**Comment by nwg-piotr** [comment]
You're right. [The latest PR](https://github.com/nwg-piotr/autotiling/pull/15/files) should have contained some description. The lines 21-22 and 74-81, added to [autotiling/main.py](https://github.com/nwg-piotr/autotiling/pull/15/files#diff-0ad13b2e532a43e2e15f6bc562b0dbe8) will only work if the script was installed with `setup.py`.

Since the script is available by PyPi, I think the manual "installation" could be removed from README. Of course you can just delete the lines I mentioned above, and it should work.

**Comment by Lqp1** [comment]
Ok thanks! I'll make an install using pip then! I prefer not to change code in my installation script as it will be harder to maintain.

**Comment by nwg-piotr** [comment]
Should be resolved now.
